# Generated by Django 3.2.20 on 2023-07-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed_images/')),
            ],
        ),
    ]
