# Generated by Django 3.2.20 on 2023-07-28 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedimage',
            old_name='processed_image',
            new_name='processed',
        ),
    ]
